### PR TITLE
Add no-module-prefix option

### PR DESCRIPTION
**Pull request by Herrie82**
Allow building module without prefix similar to: https://github.com/sailfishos/libconnman-qt/commit/625beb2b0d2ace4c59ce4e1dee5d2634640537d8

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by pvuorela** [comment]
One thing btw worrying me with these sed placeholders is the 'make qmltypes' build target which regenerates the file. That problem should be avoidable with just renaming the api but providing the backward compatibility links (e.g. like that nemo-dbus).

**Comment by monich** [comment]
I wouldn't mind to drop this `USE_MODULE_PREFIX` thing and allow both `"MeeGo.QOfono"` and `"QOfono"` in `QOfonoDeclarativePlugin::registerTypes`

**Comment by Herrie82** [comment]
> One thing btw worrying me with these sed placeholders is the 'make qmltypes' build target which regenerates the file. That problem should be avoidable with just renaming the api but providing the backward compatibility links (e.g. like that nemo-dbus).

qmlplugindump is deprecated as of 6.2.0 as per https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md

**Comment by Herrie82** [comment]
> 

That would work for me too. Just not sure how to do that? Can register with both names simply?

**Comment by Thaodan** [comment]
> That would work for me too. Just not sure how to do that? Can register with
> both names simply?

That's how it was done for the other modules.

**Comment by pvuorela** [comment]
> qmlplugindump is deprecated as of 6.2.0 as per https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md

Intesresting. However we are not going to get 6.2.0 any time soon here.

> That would work for me too. Just not sure how to do that? Can register with both names simply?

Like this.
https://github.com/sailfishos/nemo-qml-plugin-dbus/blob/master/rpm/nemo-qml-plugin-dbus-qt5.spec#L56

Can do that on the .spec and just rename the module elsewhere, or then do the same things in the .pro file side.

**Comment by Herrie82** [comment]
> That would work for me too. Just not sure how to do that? Can register with both names simply?
> That's how it was done for the other modules.

Like this one I guess? https://github.com/sailfishos/nemo-qml-plugin-dbus/blob/master/src/plugin/plugin.cpp#L42

**Comment by Herrie82** [comment]
> > qmlplugindump is deprecated as of 6.2.0 as per https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.0/release-note.md
> 
> Intesresting. However we are not going to get 6.2.0 any time soon here.
> 
> > That would work for me too. Just not sure how to do that? Can register with both names simply?
> 
> Like this. https://github.com/sailfishos/nemo-qml-plugin-dbus/blob/master/rpm/nemo-qml-plugin-dbus-qt5.spec#L56
> 
> Can do that on the .spec and just rename the module elsewhere, or then do the same things in the .pro file side.

We don't use .spec here but Yocto, but can do something similar there.

**Comment by monich** [comment]
> > That would work for me too. Just not sure how to do that? Can register with both names simply?
> > That's how it was done for the other modules.
> 
> Like this one I guess? https://github.com/sailfishos/nemo-qml-plugin-dbus/blob/master/src/plugin/plugin.cpp#L42

Yes, that's what I meant.

**Comment by Herrie82** [comment]
@monich I pushed https://github.com/sailfishos/libqofono/pull/12/commits/7ec57dfeac8dc43839ec3aa7226703cc3b2e893c happy to squash

**Review by monich — APPROVED** [review]
LGTM

**Comment by monich** [comment]
> @monich I pushed [7ec57df](https://github.com/sailfishos/libqofono/commit/7ec57dfeac8dc43839ec3aa7226703cc3b2e893c) happy to squash

Please do

**Comment by Herrie82** [comment]
@monich done :)

**Pull request merged**
